FROM python:3.11-slim

WORKDIR /app

COPY services/calc/requirements.txt .
COPY services/calc/requirements-dev.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY services/calc/app ./app
COPY services/calc/test ./test

EXPOSE 8000

CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"]
